version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: exa-payment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: exa_payment
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dev/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - exa-payment-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: exa-payment-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - exa-payment-network

  wiremock:
    image: wiremock/wiremock:latest
    container_name: exa-payment-wiremock
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./dev/wiremock:/home/wiremock
    command: ["--global-response-templating", "--verbose"]
    networks:
      - exa-payment-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: exa-payment-otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./dev/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "14268:14268"
    networks:
      - exa-payment-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: exa-payment-jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - exa-payment-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  exa-payment-network:
    driver: bridge
